// Generated by CoffeeScript 1.8.0
(function() {
    var app, express;

    express = require('express');

    app = express();

    app.use(express["static"](__dirname));

    app.listen(process.env.PORT || 3000);

}).call(this);
